/**
 * AIService — the ONLY module the rest of the app talks to about AI.
 * No prompts in UI code; every output is schema-validated before use.
 *
 * Strategy:
 *  - Structure (paths, scores, rubric results): always computed locally by
 *    the ProofEngine → deterministic, auditable, works with zero keys.
 *  - When an LLM is configured, tutor replies and qualitative feedback are
 *    generated by the provider, validated, and fall back to the engine on
 *    any error. Engine scores remain authoritative for rewards (SECURITY.md).
 */
import * as engine from './engine.js';
import { llmEnabled, llmJson } from './providers.js';
import { validate } from '../util.js';
import { KB, SKILLS, suggestDomain } from './kb.js';

const log = (...a) => console.log('[ai]', ...a);

/* ────────────────────────── learning paths ────────────────────────── */
export async function generateLearningPath(input) {
  const base = engine.generateLearningPath(input);

  if (!llmEnabled()) return { ...base, engine: 'proof-engine' };

  // LLM refinement of titles/copy only — topic sequence stays engine-driven
  // (auditable + guardable). If anything fails, engine output ships as-is.
  try {
    const kbTopics = (KB[base.skillSlug]?.topics || []).map((t) => ({ slug: t.slug, title: t.title }));
    const out = await llmJson({
      system: 'You are PROOF’s curriculum designer. You personalize learning path titles and day copy for a practical, proof-based learning app. Never invent topics outside the provided list.',
      prompt: JSON.stringify({
        goal: input.goal,
        skill: base.skillName,
        availableTopics: kbTopics,
        dayPlan: base.days.map((d) => ({ index: d.index, kind: d.kind, topics: d.items.map((i) => i.topic) })),
        task: 'Return JSON: { "title": string (max 60 chars), "description": string (max 200 chars), "dayTitles": string[] (one per day, max 40 chars each) }',
      }),
      maxTokens: 600,
    });
    const errs = validate(out, {
      type: 'object',
      required: ['title', 'description', 'dayTitles'],
      props: {
        title: { type: 'string', min: 3, max: 80 },
        description: { type: 'string', min: 3, max: 240 },
        dayTitles: { type: 'array', items: { type: 'string', min: 1, max: 60 } },
      },
    });
    if (errs.length) throw new Error('SCHEMA: ' + errs.join('; '));
    return {
      ...base,
      title: out.title,
      description: out.description,
      days: base.days.map((d, i) => ({ ...d, title: out.dayTitles[i] || d.title })),
      engine: 'llm+proof-engine',
    };
  } catch (e) {
    log('path LLM fallback:', e.message);
    return { ...base, engine: 'proof-engine' };
  }
}

/* ────────────────────────── lessons ───────────────────────────────── */
export async function generateLesson(domain, topicSlug) {
  const lesson = engine.lessonFor(domain, topicSlug);
  if (!lesson) throw new Error('TOPIC_NOT_FOUND');
  // (LLM enrichment point — engine content ships for determinism)
  return { ...lesson, engine: 'proof-engine' };
}

export function generateExercise(domain, topicSlug) {
  return engine.tutorReply({ domain, topicSlug, question: 'exercise' });
}

/* ────────────────────────── tutor ─────────────────────────────────── */
export async function tutorReply({ domain, topicSlug, question, history = [] }) {
  const local = engine.tutorReply({ domain, topicSlug, question, history });
  if (!llmEnabled()) return { ...local, engine: 'proof-engine' };

  try {
    const topic = KB[domain]?.topics?.find((t) => t.slug === topicSlug);
    const ground = topic ? {
      title: topic.title,
      tldr: topic.lesson.tldr,
      keyPoints: topic.lesson.keyPoints,
      sections: topic.lesson.sections.map((s) => ({ h: s.h, body: s.body })),
      misconception: topic.lesson.misconception,
    } : null;
    const out = await llmJson({
      system: `You are PROOF’s AI tutor. Teach like a great teacher: concise, warm, practical. NEVER give the final answer to exercises — guide with hints. Ground every reply in the provided lesson context. If the learner asks something unrelated, steer back kindly. Reply JSON: { "reply": string (max 900 chars, plain text, newlines allowed), "intent": "explain|simplify|example|exercise|hint|debug|coach" }`,
      prompt: JSON.stringify({ lessonContext: ground, recentHistory: history.slice(-6), learnerQuestion: question }),
      maxTokens: 500,
    });
    const errs = validate(out, {
      type: 'object', required: ['reply'],
      props: { reply: { type: 'string', min: 1, max: 1200 }, intent: { type: 'string' } },
    });
    if (errs.length) throw new Error('SCHEMA: ' + errs.join('; '));
    return { reply: out.reply, intent: out.intent || local.intent, exercise: null, engine: 'llm' };
  } catch (e) {
    log('tutor LLM fallback:', e.message);
    return { ...local, engine: 'proof-engine' };
  }
}

/* ────────────────────────── evaluation ────────────────────────────── */
/**
 * Deterministic rubric scoring is authoritative; the LLM (if any) may only
 * refine qualitative wording, never the score.
 */
export async function evaluateSubmission(payload, challenge, ctx = {}) {
  const result = engine.evaluateSubmission ? null : null; // (guard for tree-shaking confusion)
  const { evaluateSubmission: evaluate } = await import('./evaluators.js');
  const ruled = evaluate(payload, challenge, ctx);

  if (!llmEnabled()) return { ...ruled, engine: 'proof-engine' };

  try {
    const out = await llmJson({
      system: 'You are PROOF’s evaluation copywriter. Given a rubric evaluation and the learner’s submission, rewrite the qualitative feedback to be specific, kind, and actionable. NEVER change the score, pass status, or criterion earnings.',
      prompt: JSON.stringify({
        challengeTitle: challenge.title,
        rubricResult: { score: ruled.score, criteria: ruled.criteria, strengths: ruled.strengths, improvements: ruled.improvements, nextStep: ruled.nextStep },
        submission: JSON.stringify(payload).slice(0, 4000),
        task: 'Return JSON: { "strengths": string[] (max 4, each max 120 chars), "improvements": string[] (max 4, each max 120 chars), "nextStep": string (max 140 chars) }',
      }),
      maxTokens: 500,
    });
    const errs = validate(out, {
      type: 'object',
      required: ['strengths', 'improvements', 'nextStep'],
      props: {
        strengths: { type: 'array', items: { type: 'string', max: 160 } },
        improvements: { type: 'array', items: { type: 'string', max: 160 } },
        nextStep: { type: 'string', max: 200 },
      },
    });
    if (errs.length) throw new Error('SCHEMA: ' + errs.join('; '));
    return {
      ...ruled,
      strengths: out.strengths.slice(0, 4).length ? out.strengths.slice(0, 4) : ruled.strengths,
      improvements: out.improvements.slice(0, 4).length ? out.improvements.slice(0, 4) : ruled.improvements,
      nextStep: out.nextStep || ruled.nextStep,
      engine: 'proof-engine+llm',
    };
  } catch (e) {
    log('eval LLM fallback:', e.message);
    return { ...ruled, engine: 'proof-engine' };
  }
}

/* ────────────────────────── misc ──────────────────────────────────── */
export function identifyWeaknesses(evaluation) { return engine.identifyWeaknesses(evaluation); }

export function recommendNextSkill(userSkillSlugs) {
  return engine.recommendNextSkill(userSkillSlugs, SKILLS.map((s) => s.slug));
}

export function detectDomain(goal) { return suggestDomain(goal); }

export { engine };
